/** Catálogo CIE-10 capítulo K00–K14 (enfermedades de la cavidad bucal). DC-17. */
export const CIE10_K = [
  { c: "K00.0", d: "Anodoncia" },
  { c: "K00.1", d: "Dientes supernumerarios" },
  { c: "K00.2", d: "Anomalías de tamaño y forma de los dientes" },
  { c: "K00.3", d: "Dientes moteados" },
  { c: "K00.4", d: "Alteraciones en la formación de los dientes" },
  { c: "K00.5", d: "Alteraciones hereditarias de la estructura dentaria" },
  { c: "K00.6", d: "Alteraciones en la erupción de los dientes" },
  { c: "K00.7", d: "Síndrome de la erupción dentaria" },
  { c: "K00.8", d: "Otros trastornos del desarrollo de los dientes" },
  { c: "K00.9", d: "Trastorno del desarrollo de los dientes, no especificado" },
  { c: "K01.0", d: "Dientes incluidos" },
  { c: "K01.1", d: "Dientes impactados" },
  { c: "K02.0", d: "Caries limitada al esmalte" },
  { c: "K02.1", d: "Caries de la dentina" },
  { c: "K02.2", d: "Caries del cemento" },
  { c: "K02.3", d: "Caries detenida" },
  { c: "K02.5", d: "Caries con exposición de la pulpa" },
  { c: "K02.8", d: "Otras caries dentales" },
  { c: "K02.9", d: "Caries dental, no especificada" },
  { c: "K03.0", d: "Atrición excesiva de los dientes" },
  { c: "K03.1", d: "Abrasión de los dientes" },
  { c: "K03.2", d: "Erosión de los dientes" },
  { c: "K03.3", d: "Reabsorción patológica de los dientes" },
  { c: "K03.4", d: "Hipercementosis" },
  { c: "K03.5", d: "Anquilosis de los dientes" },
  { c: "K03.6", d: "Depósitos [acreciones] en los dientes" },
  { c: "K03.7", d: "Cambios posteriores a la erupción del color de los tejidos duros dentales" },
  { c: "K03.8", d: "Otras enfermedades especificadas de los tejidos duros de los dientes" },
  { c: "K03.9", d: "Enfermedad de los tejidos duros de los dientes, no especificada" },
  { c: "K04.0", d: "Pulpitis" },
  { c: "K04.1", d: "Necrosis de la pulpa" },
  { c: "K04.2", d: "Degeneración de la pulpa" },
  { c: "K04.3", d: "Formación anormal de tejido duro en la pulpa" },
  { c: "K04.4", d: "Periodontitis apical aguda originada en la pulpa" },
  { c: "K04.5", d: "Periodontitis apical crónica" },
  { c: "K04.6", d: "Absceso periapical con fístula" },
  { c: "K04.7", d: "Absceso periapical sin fístula" },
  { c: "K04.8", d: "Quiste radicular" },
  { c: "K04.9", d: "Otras enfermedades y las no especificadas de la pulpa y del tejido periapical" },
  { c: "K05.0", d: "Gingivitis aguda" },
  { c: "K05.1", d: "Gingivitis crónica" },
  { c: "K05.2", d: "Periodontitis aguda" },
  { c: "K05.3", d: "Periodontitis crónica" },
  { c: "K05.4", d: "Periodontosis" },
  { c: "K05.5", d: "Otras enfermedades periodontales" },
  { c: "K05.6", d: "Enfermedad de la encía y del periodonto, no especificada" },
  { c: "K06.0", d: "Retracción gingival" },
  { c: "K06.1", d: "Hiperplasia gingival" },
  { c: "K06.2", d: "Lesiones de la encía y de la zona edéntula asociadas con traumatismo" },
  { c: "K06.8", d: "Otros trastornos especificados de la encía y de la zona edéntula" },
  { c: "K06.9", d: "Trastorno de la encía y de la zona edéntula, no especificado" },
  { c: "K07.0", d: "Anomalías importantes del tamaño de los maxilares" },
  { c: "K07.1", d: "Anomalías de la relación entre los maxilares y la base del cráneo" },
  { c: "K07.2", d: "Anomalías de la relación entre los arcos dentarios" },
  { c: "K07.3", d: "Anomalías de la posición del diente" },
  { c: "K07.4", d: "Maloclusión, no especificada" },
  { c: "K07.5", d: "Anomalías dentofaciales funcionales" },
  { c: "K07.6", d: "Trastorno de la articulación temporomandibular" },
  { c: "K07.8", d: "Otras anomalías dentofaciales" },
  { c: "K07.9", d: "Anomalía dentofacial, no especificada" },
  { c: "K08.0", d: "Exfoliación de los dientes debida a causas sistémicas" },
  { c: "K08.1", d: "Pérdida de dientes debida a accidente, extracción o enfermedad periodontal local" },
  { c: "K08.2", d: "Atrofia del reborde alveolar desdentado" },
  { c: "K08.3", d: "Raíz dental retenida" },
  { c: "K08.8", d: "Otros trastornos especificados de los dientes y de sus estructuras de sostén" },
  { c: "K08.9", d: "Trastorno de los dientes y de sus estructuras de sostén, no especificado" },
  { c: "K09.0", d: "Quistes originados por el desarrollo de los dientes" },
  { c: "K09.1", d: "Quistes de las fisuras (no odontogénicos)" },
  { c: "K09.2", d: "Otros quistes de los maxilares" },
  { c: "K09.8", d: "Otros quistes de la región bucal, no clasificados en otra parte" },
  { c: "K09.9", d: "Quiste de la región bucal, sin otra especificación" },
  { c: "K10.0", d: "Trastornos del desarrollo de los maxilares" },
  { c: "K10.1", d: "Granuloma central de células gigantes" },
  { c: "K10.2", d: "Afecciones inflamatorias de los maxilares" },
  { c: "K10.3", d: "Alveolitis del maxilar" },
  { c: "K10.8", d: "Otros trastornos especificados de los maxilares" },
  { c: "K10.9", d: "Trastorno de los maxilares, no especificado" },
  { c: "K11.0", d: "Atrofia de glándula salival" },
  { c: "K11.1", d: "Hipertrofia de glándula salival" },
  { c: "K11.2", d: "Sialadenitis" },
  { c: "K11.3", d: "Absceso de glándula salival" },
  { c: "K11.4", d: "Fístula de glándula salival" },
  { c: "K11.5", d: "Sialolitiasis" },
  { c: "K11.6", d: "Mucocele de glándula salival" },
  { c: "K11.7", d: "Alteraciones de la secreción salival" },
  { c: "K11.8", d: "Otras enfermedades de las glándulas salivales" },
  { c: "K11.9", d: "Enfermedad de glándula salival, no especificada" },
  { c: "K12.0", d: "Aftas bucales recidivantes" },
  { c: "K12.1", d: "Otras formas de estomatitis" },
  { c: "K12.2", d: "Celulitis y absceso de boca" },
  { c: "K13.0", d: "Enfermedades de los labios" },
  { c: "K13.1", d: "Mordedura de la mejilla y del labio" },
  { c: "K13.2", d: "Leucoplasia y otras alteraciones del epitelio bucal, incluyendo la lengua" },
  { c: "K13.3", d: "Leucoplasia pilosa" },
  { c: "K13.4", d: "Lesiones granulomatosas y granulomatosimiles de la mucosa bucal" },
  { c: "K13.5", d: "Fibrosis de la submucosa bucal" },
  { c: "K13.6", d: "Hiperplasia irritativa de la mucosa bucal" },
  { c: "K13.7", d: "Otras lesiones y las no especificadas de la mucosa bucal" },
  { c: "K14.0", d: "Glositis" },
  { c: "K14.1", d: "Lengua geográfica" },
  { c: "K14.2", d: "Glositis romboidea mediana" },
  { c: "K14.3", d: "Hipertrofia de las papilas linguales" },
  { c: "K14.4", d: "Atrofia de las papilas linguales" },
  { c: "K14.5", d: "Lengua plegada" },
  { c: "K14.6", d: "Glosodinia" },
  { c: "K14.8", d: "Otras enfermedades de la lengua" },
  { c: "K14.9", d: "Enfermedad de la lengua, no especificada" },
];

export function buscarCie10(q, limit = 12) {
  const s = String(q || "").trim().toLowerCase();
  if (!s) return CIE10_K.slice(0, limit);
  return CIE10_K.filter((x) => x.c.toLowerCase().includes(s) || x.d.toLowerCase().includes(s)).slice(0, limit);
}
